// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageHeader.proto

#include "messageHeader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace CKPacket {
PROTOBUF_CONSTEXPR messageHeader::messageHeader(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.arr_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.userid_)*/0u
  , /*decltype(_impl_.arrsize_)*/0u} {}
struct messageHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR messageHeaderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~messageHeaderDefaultTypeInternal() {}
  union {
    messageHeader _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 messageHeaderDefaultTypeInternal _messageHeader_default_instance_;
}  // namespace CKPacket
static ::_pb::Metadata file_level_metadata_messageHeader_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_messageHeader_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_messageHeader_2eproto = nullptr;

const uint32_t TableStruct_messageHeader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _impl_.userid_),
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _impl_.arr_),
  PROTOBUF_FIELD_OFFSET(::CKPacket::messageHeader, _impl_.arrsize_),
  2,
  0,
  1,
  3,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::CKPacket::messageHeader)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::CKPacket::_messageHeader_default_instance_._instance,
};

const char descriptor_table_protodef_messageHeader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023messageHeader.proto\022\010CKPacket\"\207\001\n\rmess"
  "ageHeader\022\023\n\006userId\030\001 \001(\rH\000\210\001\001\022\021\n\004type\030\002"
  " \001(\tH\001\210\001\001\022\020\n\003arr\030\003 \001(\014H\002\210\001\001\022\024\n\007arrSize\030\004"
  " \001(\rH\003\210\001\001B\t\n\007_userIdB\007\n\005_typeB\006\n\004_arrB\n\n"
  "\010_arrSizeb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_messageHeader_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_messageHeader_2eproto = {
    false, false, 177, descriptor_table_protodef_messageHeader_2eproto,
    "messageHeader.proto",
    &descriptor_table_messageHeader_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_messageHeader_2eproto::offsets,
    file_level_metadata_messageHeader_2eproto, file_level_enum_descriptors_messageHeader_2eproto,
    file_level_service_descriptors_messageHeader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_messageHeader_2eproto_getter() {
  return &descriptor_table_messageHeader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_messageHeader_2eproto(&descriptor_table_messageHeader_2eproto);
namespace CKPacket {

// ===================================================================

class messageHeader::_Internal {
 public:
  using HasBits = decltype(std::declval<messageHeader>()._impl_._has_bits_);
  static void set_has_userid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_arr(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_arrsize(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

messageHeader::messageHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CKPacket.messageHeader)
}
messageHeader::messageHeader(const messageHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  messageHeader* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
    , decltype(_impl_.arr_){}
    , decltype(_impl_.userid_){}
    , decltype(_impl_.arrsize_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_type()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.arr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.arr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_arr()) {
    _this->_impl_.arr_.Set(from._internal_arr(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.userid_, &from._impl_.userid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.arrsize_) -
    reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.arrsize_));
  // @@protoc_insertion_point(copy_constructor:CKPacket.messageHeader)
}

inline void messageHeader::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.type_){}
    , decltype(_impl_.arr_){}
    , decltype(_impl_.userid_){0u}
    , decltype(_impl_.arrsize_){0u}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.arr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.arr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

messageHeader::~messageHeader() {
  // @@protoc_insertion_point(destructor:CKPacket.messageHeader)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void messageHeader::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  _impl_.arr_.Destroy();
}

void messageHeader::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void messageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:CKPacket.messageHeader)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.type_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.arr_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.userid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.arrsize_) -
        reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.arrsize_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* messageHeader::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 userId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_userid(&has_bits);
          _impl_.userid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "CKPacket.messageHeader.type"));
        } else
          goto handle_unusual;
        continue;
      // optional bytes arr = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_arr();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 arrSize = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_arrsize(&has_bits);
          _impl_.arrsize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* messageHeader::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CKPacket.messageHeader)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 userId = 1;
  if (_internal_has_userid()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_userid(), target);
  }

  // optional string type = 2;
  if (_internal_has_type()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "CKPacket.messageHeader.type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_type(), target);
  }

  // optional bytes arr = 3;
  if (_internal_has_arr()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_arr(), target);
  }

  // optional uint32 arrSize = 4;
  if (_internal_has_arrsize()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_arrsize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CKPacket.messageHeader)
  return target;
}

size_t messageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CKPacket.messageHeader)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string type = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_type());
    }

    // optional bytes arr = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_arr());
    }

    // optional uint32 userId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_userid());
    }

    // optional uint32 arrSize = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_arrsize());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData messageHeader::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    messageHeader::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*messageHeader::GetClassData() const { return &_class_data_; }


void messageHeader::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<messageHeader*>(&to_msg);
  auto& from = static_cast<const messageHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CKPacket.messageHeader)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_type(from._internal_type());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_arr(from._internal_arr());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.userid_ = from._impl_.userid_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.arrsize_ = from._impl_.arrsize_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void messageHeader::CopyFrom(const messageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CKPacket.messageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool messageHeader::IsInitialized() const {
  return true;
}

void messageHeader::InternalSwap(messageHeader* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.arr_, lhs_arena,
      &other->_impl_.arr_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(messageHeader, _impl_.arrsize_)
      + sizeof(messageHeader::_impl_.arrsize_)
      - PROTOBUF_FIELD_OFFSET(messageHeader, _impl_.userid_)>(
          reinterpret_cast<char*>(&_impl_.userid_),
          reinterpret_cast<char*>(&other->_impl_.userid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata messageHeader::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_messageHeader_2eproto_getter, &descriptor_table_messageHeader_2eproto_once,
      file_level_metadata_messageHeader_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace CKPacket
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CKPacket::messageHeader*
Arena::CreateMaybeMessage< ::CKPacket::messageHeader >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CKPacket::messageHeader >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
