// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system.proto

#include "system.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace CKPacket {
PROTOBUF_CONSTEXPR Invalid::Invalid(
    ::_pbi::ConstantInitialized) {}
struct InvalidDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvalidDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvalidDefaultTypeInternal() {}
  union {
    Invalid _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvalidDefaultTypeInternal _Invalid_default_instance_;
PROTOBUF_CONSTEXPR SystemEnd::SystemEnd(
    ::_pbi::ConstantInitialized) {}
struct SystemEndDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SystemEndDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SystemEndDefaultTypeInternal() {}
  union {
    SystemEnd _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SystemEndDefaultTypeInternal _SystemEnd_default_instance_;
PROTOBUF_CONSTEXPR SYSTEM_USER_DISCONNECT::SYSTEM_USER_DISCONNECT(
    ::_pbi::ConstantInitialized) {}
struct SYSTEM_USER_DISCONNECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SYSTEM_USER_DISCONNECTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SYSTEM_USER_DISCONNECTDefaultTypeInternal() {}
  union {
    SYSTEM_USER_DISCONNECT _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SYSTEM_USER_DISCONNECTDefaultTypeInternal _SYSTEM_USER_DISCONNECT_default_instance_;
PROTOBUF_CONSTEXPR SYSTEM_USER_CONNECT::SYSTEM_USER_CONNECT(
    ::_pbi::ConstantInitialized) {}
struct SYSTEM_USER_CONNECTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SYSTEM_USER_CONNECTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SYSTEM_USER_CONNECTDefaultTypeInternal() {}
  union {
    SYSTEM_USER_CONNECT _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SYSTEM_USER_CONNECTDefaultTypeInternal _SYSTEM_USER_CONNECT_default_instance_;
}  // namespace CKPacket
static ::_pb::Metadata file_level_metadata_system_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_system_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_system_2eproto = nullptr;

const uint32_t TableStruct_system_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CKPacket::Invalid, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CKPacket::SystemEnd, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CKPacket::SYSTEM_USER_DISCONNECT, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CKPacket::SYSTEM_USER_CONNECT, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::CKPacket::Invalid)},
  { 6, -1, -1, sizeof(::CKPacket::SystemEnd)},
  { 12, -1, -1, sizeof(::CKPacket::SYSTEM_USER_DISCONNECT)},
  { 18, -1, -1, sizeof(::CKPacket::SYSTEM_USER_CONNECT)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::CKPacket::_Invalid_default_instance_._instance,
  &::CKPacket::_SystemEnd_default_instance_._instance,
  &::CKPacket::_SYSTEM_USER_DISCONNECT_default_instance_._instance,
  &::CKPacket::_SYSTEM_USER_CONNECT_default_instance_._instance,
};

const char descriptor_table_protodef_system_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014system.proto\022\010CKPacket\"\t\n\007Invalid\"\013\n\tS"
  "ystemEnd\"\030\n\026SYSTEM_USER_DISCONNECT\"\025\n\023SY"
  "STEM_USER_CONNECTb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_system_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_system_2eproto = {
    false, false, 105, descriptor_table_protodef_system_2eproto,
    "system.proto",
    &descriptor_table_system_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_system_2eproto::offsets,
    file_level_metadata_system_2eproto, file_level_enum_descriptors_system_2eproto,
    file_level_service_descriptors_system_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_system_2eproto_getter() {
  return &descriptor_table_system_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_system_2eproto(&descriptor_table_system_2eproto);
namespace CKPacket {

// ===================================================================

class Invalid::_Internal {
 public:
};

Invalid::Invalid(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:CKPacket.Invalid)
}
Invalid::Invalid(const Invalid& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Invalid* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CKPacket.Invalid)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Invalid::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Invalid::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Invalid::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_2eproto_getter, &descriptor_table_system_2eproto_once,
      file_level_metadata_system_2eproto[0]);
}

// ===================================================================

class SystemEnd::_Internal {
 public:
};

SystemEnd::SystemEnd(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:CKPacket.SystemEnd)
}
SystemEnd::SystemEnd(const SystemEnd& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  SystemEnd* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CKPacket.SystemEnd)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SystemEnd::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SystemEnd::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata SystemEnd::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_2eproto_getter, &descriptor_table_system_2eproto_once,
      file_level_metadata_system_2eproto[1]);
}

// ===================================================================

class SYSTEM_USER_DISCONNECT::_Internal {
 public:
};

SYSTEM_USER_DISCONNECT::SYSTEM_USER_DISCONNECT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:CKPacket.SYSTEM_USER_DISCONNECT)
}
SYSTEM_USER_DISCONNECT::SYSTEM_USER_DISCONNECT(const SYSTEM_USER_DISCONNECT& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  SYSTEM_USER_DISCONNECT* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CKPacket.SYSTEM_USER_DISCONNECT)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SYSTEM_USER_DISCONNECT::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SYSTEM_USER_DISCONNECT::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata SYSTEM_USER_DISCONNECT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_2eproto_getter, &descriptor_table_system_2eproto_once,
      file_level_metadata_system_2eproto[2]);
}

// ===================================================================

class SYSTEM_USER_CONNECT::_Internal {
 public:
};

SYSTEM_USER_CONNECT::SYSTEM_USER_CONNECT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:CKPacket.SYSTEM_USER_CONNECT)
}
SYSTEM_USER_CONNECT::SYSTEM_USER_CONNECT(const SYSTEM_USER_CONNECT& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  SYSTEM_USER_CONNECT* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CKPacket.SYSTEM_USER_CONNECT)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SYSTEM_USER_CONNECT::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SYSTEM_USER_CONNECT::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata SYSTEM_USER_CONNECT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_system_2eproto_getter, &descriptor_table_system_2eproto_once,
      file_level_metadata_system_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace CKPacket
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CKPacket::Invalid*
Arena::CreateMaybeMessage< ::CKPacket::Invalid >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CKPacket::Invalid >(arena);
}
template<> PROTOBUF_NOINLINE ::CKPacket::SystemEnd*
Arena::CreateMaybeMessage< ::CKPacket::SystemEnd >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CKPacket::SystemEnd >(arena);
}
template<> PROTOBUF_NOINLINE ::CKPacket::SYSTEM_USER_DISCONNECT*
Arena::CreateMaybeMessage< ::CKPacket::SYSTEM_USER_DISCONNECT >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CKPacket::SYSTEM_USER_DISCONNECT >(arena);
}
template<> PROTOBUF_NOINLINE ::CKPacket::SYSTEM_USER_CONNECT*
Arena::CreateMaybeMessage< ::CKPacket::SYSTEM_USER_CONNECT >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CKPacket::SYSTEM_USER_CONNECT >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
